### ISSUE TITLE
explanation about enumerate

### ISSUE THREAD

**Issue by Tami8264** [r0f1/adventofcode2020#1]
in advent of code day 1 solution, you wrote:
``` 
for i, n1 in enumerate(l):
    for j, n2 in enumerate(l[i+1:]):
```
what i want to know is that, does l[i+1] means the indexing will be different in n2? i mean if n1 indexing is like
0 1971
1 1671
will n2 indexing be like
1 1971
2 1671
??

**Comment by r0f1** [comment]
Hi,
The built-in function `enumerate()` expects an iterable as its single argument and when looped over, returns a number (starting from zero) plus an element from that iterable. For example:
```python
>>> a = [4,8,13,17,19]
>>> list(enumerate(a))
[(0, 4), (1, 8), (2, 13), (3, 17), (4, 19)]
```
`enumerate()` always starts at zero. That means it also starts at zero when I feed it a slice of a list.
```python
>>> list(enumerate(a[2:]))
[(0, 13), (1, 17), (2, 19)]
```
Note that (like you suggested) the indexing is indeed different. In the above example `13` gets assigned `2`, while in the example below  `13` gets assigned `0`.

Now let's consider this code:
```python
a = [4,8,13,17,19]
for i, n1 in enumerate(a):
    for j, n2 in enumerate(a[i+1:]):
        print(i,j,n1,n2)
```
which prints
```
0 0 4 8
0 1 4 13
0 2 4 17
0 3 4 19
1 0 8 13
1 1 8 17
1 2 8 19
2 0 13 17
2 1 13 19
3 0 17 19
```
Here you can see what all the values of the outer loop variable `i` and the inner loop variable `j` are (first and second column, respectively) and which two values are assigned to `n1` and `n2` (the last two columns).

**Comment by Tami8264** [comment]
Thank you so much for explaining this to me! If you don't mind can I
sometimes bother you about few things I don't understand?
